export const fonts = {
  Montserrat_Black: 'Montserrat-Black.ttf',
  Montserrat_BlackItalic: 'Montserrat-BlackItalic.ttf',
  Montserrat_Bold: 'Montserrat-Bold.ttf',
  Montserrat_BoldItalic: 'Montserrat-BoldItalic.ttf',
  Montserrat_ExtraBold: 'Montserrat-ExtraBold.ttf',
  Montserrat_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic.ttf',
  Montserrat_ExtraLight: 'Montserrat-ExtraLight.ttf',
  Montserrat_ExtraLightItalic: 'Montserrat-ExtraLightItalic.ttf',
  Montserrat_Italic: 'Montserrat-Italic.ttf',
  Montserrat_Light: 'Montserrat-Light.ttf',
  Montserrat_LightItalic: 'Montserrat-LightItalic.ttf',
  Montserrat_Medium: 'Montserrat-Medium.ttf',
  Montserrat_MediumItalic: 'Montserrat-MediumItalic.ttf',
  Montserrat_Regular: 'Montserrat-Regular.ttf',
  Montserrat_SemiBold: 'Montserrat-SemiBold.ttf',
  Montserrat_SemiBoldItalic: 'Montserrat-SemiBoldItalic.ttf',
  Montserrat_Thin: 'Montserrat-Thin.ttf',
  Montserrat_ThinItalic: 'Montserrat-ThinItalic.ttf',
};
